### ISSUE TITLE
Possible to do a vue.js  (or nuxt.js) version?

### ISSUE THREAD

**Issue by connecteev** [tpaksu/laravel-todobar#1]
THis is very cool, but I wouldnt use it in it's current state unless it's done in vue.js (or nuxt) instead of blade. I like that the backend is in laravel, though. Possible to have this in vue?

**Comment by tpaksu** [comment]
I'll try in a few days, shouldn't be hard :)

**Comment by connecteev** [comment]
A laravel+ nuxt version would be even better. Thanks..let me know and i'll try it out when ready!

**Comment by tpaksu** [comment]
Nuxt seems a little bit overkill for this. I'm going to use vue.

**Comment by connecteev** [comment]
ok, cool..will try it when you're ready

**Comment by tpaksu** [comment]
Can you check https://github.com/tpaksu/laravel-todobar-vue? I'm not an expert Vue developer btw.

**Comment by connecteev** [comment]
@tpaksu thank you..I will! I'll leave my feedback on that repo for you. Look forward to using this...vue gives a lot more control than blade, and I look forward to that package improving.

**Comment by tpaksu** [comment]
@connecteev any thoughts about the plugin?
